# Generated by Django 2.2.2 on 2019-06-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_auto_20190613_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerpublish',
            name='pastflag',
            field=models.BooleanField(default=False),
        ),
    ]
