# Generated by Django 2.2.2 on 2019-06-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0003_trainerpublish_pastflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrecord',
            name='pastflag',
            field=models.BooleanField(default=False),
        ),
    ]
