# Generated by Django 2.2.2 on 2019-06-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0004_bookrecord_pastflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrecord',
            name='remarks',
            field=models.CharField(default='', max_length=50),
        ),
    ]
