# Generated by Django 2.2.2 on 2019-06-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0005_buyrecord_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceRecord',
            fields=[
                ('timeid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=10)),
                ('remarks', models.CharField(max_length=50)),
            ],
        ),
    ]
