# Generated by Django 2.2.2 on 2019-06-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0006_financerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='financerecord',
            name='date',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='remarks',
            field=models.CharField(default='', max_length=50),
        ),
    ]
